name: 'Read Json Properties Action'
description: 'Reads properties and exposes them to the github action'
branding:
  icon: 'box'  
  color: 'green'
inputs:
  path:
    default: "package.json"
    description: 'Path to the json file'
  json:
    default: "{}"
    description: 'json input'
  properties:
    description: 'Property or an array to read eg: "[name, version, repository.url]" or "name"'
    required: true
  transformNested:
    description: "A sign that replaces `.` for ouput values"
    default: "_"
outputs:
  values:
    description: "Each property is accessed via it's property name using outputs value eg: {{steps.read_property.outputs.name}}. If a property is nested `.` is replaced with '_' by default eg: {{steps.read_property.repository_url}}"
runs:
  using: 'node16'
  main: 'index.js'