
name: Zip Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Read Json Properties Action
        uses: Muchaszewski/read-json-action@main
        id: json
        with:
          path: "./tests/test.json"
          properties: "name, version"

      - uses: nick-fields/assert-action@v1
        with:
          expected: value
          actual: ${{ steps.json.outputs.name }}
          comparison: exact

      - uses: nick-fields/assert-action@v1
        with:
          expected: 1.0.0
          actual: ${{ steps.json.outputs.version }}
          comparison: exact